### ISSUE TITLE
Change of name

### ISSUE THREAD

**Issue by genofire** [ffnord/mesh-announce#19]
now this project support also respondd -> we should eliminate the word alfred out of the repo name.
Some ideas:
- ffnord-announce
- gateway-annouce
- vpn-announce
- mesh-announce

**Comment by jplitza** [comment]
There is nothing specific to ffnord, gateways or VPNs, so all of these three would be strange choices as well. If we are willing to focus on respondd and ignore alfred altogether, I'd opt for "pyrespondd", otherwise something generic like "mesh-announce" or "server-announce" would be most fitting.

**Comment by genofire** [comment]
greate, lets take something of this names - but do not put respondd or alfred into the name :)

**Comment by genofire** [comment]
or
- node-info-announce

**Comment by jplitza** [comment]
Inspired by FreifunkBremen/yanic#24:
Yanina: Yet another node information network announcer
(scnr, this isn't a serious proposal, for the same reason I dislike node-info-announce: It's for servers, not for nodes)

**Comment by genofire** [comment]
Could someone of ffnord say somthing? ^^

**Comment by rubo77** [comment]
What about mesh-node-info-announce?

**Comment by jplitza** [comment]
node-info-collector misleadingly sounds like something is collected from multiple nodes. mesh-node-info-announce again has mesh in it.

If nobody objects, I will rename this project to "pyrespondd" the next time I visit here.

**Comment by rubo77** [comment]
But the it has "respondd" in it but not Alfred.

I think we Should choose a name that is service independent:

      meta-announcer

**Comment by rubo77** [comment]
- -info-announce

**Comment by jplitza** [comment]
Reading all proposals again, I'd prefer mesh-announce. It's agnostic of the way of transportation (respondd vs. alfred) as well as the machine it is running on (supernode vs. gateway vs. server vs. node) and the connection method (vpn vs. wireless vs. wired vs. virtio).

**Comment by genofire** [comment]
Okay, let's rename it - if somebody other would care, he should already answer.

**Comment by genofire** [comment]
Please change also the description.
