### ISSUE TITLE
Add more detailed info to README how to configure for respondd

### ISSUE THREAD

**Issue by rubo77** [ffnord/mesh-announce#24]
There seems something essential missing

Do I have to add some options to the respondd systemd service file?

For example, how do I define, which vpn-gateway-hostname will be transmitted via respondd to the meshviewer? How and where do I define the network interfaces?

**Comment by mweinelt** [comment]
>  vpn-gateway-hostname 
https://github.com/ffnord/mesh-announce/blob/master/nodeinfo.d/hostname

> How and where do I define the network interfaces?
```
# python3 /opt/mesh-announce/respondd.py -i clientbr -i mesh-vpn -b bat0
```

**Comment by rubo77** [comment]
must i change the command in the file `/etc/systemd/system/respondd.service` ?

and do I have to add the PATH there too?

**Comment by rubo77** [comment]
I tried this in `/etc/systemd/system/respondd.service` now:

     ExecStart=/opt/mesh-announce/respondd.py -i bat-ffki -i ffki-mvpn -b br-ffki

How long, until it will show up in the map as vpn2 instead of deadbeef02?

For example here it should be the selected gateway:  https://map.freifunk.in-kiel.de/#/c03f0e7ab29d

**Comment by genofire** [comment]
could you dump `ip l` here?

**Comment by rubo77** [comment]
```
$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:50:56:00:79:4d brd ff:ff:ff:ff:ff:ff
3: br-ffki: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether de:ad:be:ef:ff:02 brd ff:ff:ff:ff:ff:ff
4: ffki-mvpn: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1280 qdisc pfifo_fast master bat-ffki state UNKNOWN mode DEFAULT group default qlen 500
    link/ether de:ad:be:ef:ff:02 brd ff:ff:ff:ff:ff:ff
5: bat-ffki: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-ffki state UNKNOWN mode DEFAULT group default 
    link/ether de:ad:be:ef:ff:02 brd ff:ff:ff:ff:ff:ff
9: tun-anonvpn: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 100
    link/none 
```

**Comment by rubo77** [comment]
ich probiere jetzt noch mal 

    ExecStart=/opt/mesh-announce/respondd.py -i br-ffki -i ffki-mvpn -b bat-ffki

**Comment by mweinelt** [comment]
Firewall?

**Comment by rubo77** [comment]
```
$ sudo iptables-save|grep 1001
-A bat-input -p udp -m udp --dport 1001 -m comment --comment respondd -j ACCEPT
-A mesh-input -p udp -m udp --dport 1001 -m comment --comment respondd -j ACCEPT
```

**Comment by genofire** [comment]
das -d fehlt oder das setzen des WorkingDirectory
