### ISSUE TITLE
Aktueller Stand nicht lauffähig auf kernel 4.x mit batman 2018

### ISSUE THREAD

**Issue by Tarnatos** [ffnord/mesh-announce#40]
Moin,

der aktuelle Stand ist nicht lauffähig.

`Jan 08 15:41:29 0.gw.iz systemd[1]: Starting Respondd...
Jan 08 15:41:29 0.gw.iz systemd[1]: Started Respondd.
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: Traceback (most recent call last):
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "/opt/mesh-announce/respondd.py", line 70, in <module>
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: get_handler(get_providers(args.directory), {'batadv_dev': args.batadv_iface, 'mesh_ipv4': args.mesh_ipv4})
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "/opt/mesh-announce/providers/__init__.py", line 153, in get_providers
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: provider = Provider.from_directory(directory, dir)
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "/opt/mesh-announce/providers/__init__.py", line 121, in from_directory
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: src = Source.from_file([dirname] + path[0] + [fname], path[0] + [fname])
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "/opt/mesh-announce/providers/__init__.py", line 88, in from_file
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: module = import_module(relpath, __package__)
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: return _bootstrap._gcd_import(name[level:], package, level)
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
Jan 08 15:41:29 0.gw.iz respondd.py[1080]: ImportError: No module named 'providers.providers'
Jan 08 15:41:29 0.gw.iz systemd[1]: respondd.service: main process exited, code=exited, status=1/FAILURE
Jan 08 15:41:29 0.gw.iz systemd[1]: Unit respondd.service entered failed state.
Jan 08 15:41:30 0.gw.iz systemd[1]: respondd.service holdoff time over, scheduling restart.
Jan 08 15:41:30 0.gw.iz systemd[1]: Stopping Respondd...
Jan 08 15:41:30 0.gw.iz systemd[1]: Starting Respondd...
Jan 08 15:41:30 0.gw.iz systemd[1]: Started Respondd.
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: Traceback (most recent call last):
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: File "/opt/mesh-announce/respondd.py", line 70, in <module>
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: get_handler(get_providers(args.directory), {'batadv_dev': args.batadv_iface, 'mesh_ipv4': args.mesh_ipv4})
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: File "/opt/mesh-announce/providers/__init__.py", line 153, in get_providers
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: provider = Provider.from_directory(directory, dir)
Jan 08 15:41:30 0.gw.iz respondd.py[1209]: File "/opt/mesh-announce/providers/__init__.py", line 121, in from_directory
`
commit cbb584b4784adff085a9eb32a0af4864a87f0a9c geht noch einwandfrei.

**Comment by genofire** [comment]
Mit welchen Parametern rufst du `respondd.py` auf ?

Vermutung: `-d /opt/mesh-announce` statt `-d /opt/mesh-announce/providers`

https://github.com/ffnord/mesh-announce/compare/cbb584b4784adff085a9eb32a0af4864a87f0a9c...master

Du hast wahrscheinlich nicht die `respondd.service` geupdated, wie in der README.md erwähnt.

**Comment by Tarnatos** [comment]
Wurde gestern frisch gelconed auf einen Server auf dem das nie lief.

**Comment by genofire** [comment]
Wie sieht die ExecStart im system unit file aus? (Oder `systemctl status respondd` oder `ps -aux | grep respondd`)

**Comment by Tarnatos** [comment]
https://github.com/ffnord/mesh-announce/blob/master/respondd.service

So.

**Comment by Tarnatos** [comment]
Der Tip war gut. Hatte das Start-Script nicht angepasst nun läuft es danke!
