### ISSUE TITLE
listen with different address and interfaces

### ISSUE THREAD

**Issue by genofire** [ffnord/mesh-announce#42]
It need to listen with `ff05::2:1001` (global on client net) and `ff02::2:1001` (statuspage, inside tunnel) in different interface.

https://github.com/freifunk-gluon/gluon/commit/59a44274cb00e88e3420b4c9c4303ca70f16b211

**Comment by TobleMiner** [comment]
#43 Allows for specification of an arbitrary number of multicast interfaces and groups

**Comment by jplitza** [comment]
@TobleMiner Yeah, so why the re-open?

**Comment by TobleMiner** [comment]
@jplitza I'd have appreciated some input regarding changes to the default `respondd.service` file. I can make the required adjustments myself though.
