### ISSUE TITLE
static values provider

### ISSUE THREAD

**Issue by anoymouserver** [ffnord/mesh-announce#45]
How can I send additional static values like geo coordinates?
The solution mentioned in #16 doesn't work anymore since the rewrite.

Do I need to write a python file for each additional value (like the `providers/nodeinfo/vpn.py`)?

**Comment by jplitza** [comment]
Yes, you have to create a python file. We actually ship one file that just sends a static value (namely True): https://github.com/ffnord/mesh-announce/blob/55ce8b580f4c25f8c0f75d6b05227fee0b8a96a0/providers/nodeinfo/software/fastd/enabled.py#L1-L5
