### ISSUE TITLE
Compatibility to batctl >= 2019.3

### ISSUE THREAD

**Issue by margau** [ffnord/mesh-announce#50]
Hello together,
with batman-adv the batctl-option "-m <device>" is replaced with "meshif <device>" (see https://www.open-mesh.org/news/92).
As of now, this only triggers some deprecation warnings.

For fixing this replacing "-m" with "meshif" should work - but this probably breaks compatibility with BATMAN-ADV < 2019.3.

How should this be resolved?

Best regards
margau

**Comment by TobleMiner** [comment]
Hard to tell. I'd love to have auto-detection for it but looks like we would have to start parsing the `batctl -v` output to do so. While I don't like that idea I don't feel like having the user specify the version is a solution either. I'll make a PR for parsing the version

**Comment by TobleMiner** [comment]
See #51 and test, please

**Comment by AiyionPrime** [comment]
Tested both #51 and #64.

batctl 2021.0 debian buster: no warnings left
