### ISSUE TITLE
[FEATURE] Allow combination of separate domain codes for a multi domain setup

### ISSUE THREAD

**Issue by herbetom** [ffnord/mesh-announce#56]
Currently there is no way to use the new `-n <domain code>` [option](https://github.com/ffnord/mesh-announce/pull/55) (thanks for implementing that) in a multi domain setup. Unless you start for every domain a seperate instance of mesh-announce. 

In the example for a multi-domain setup:
`respondd.py -d /opt/mesh-announce/providers -i meshvpn-one -i br-one -i bat-one -b bat-one -i meshvpn-two -i br-two -i bat-two -b bat-two -i meshvpn-three -i br-three -i bat-three -b bat-three`
it seems to be suggested not to run multiple instances of mesh-announce for multi domain. 

I don't know which would be the best way to include this information, but somehow you should be able to do this.

This also extends to other options, but `-n` seems to me like something esential for multi domain.

**Comment by AiyionPrime** [comment]
ffh has the same interest. What do you thin about an option e.g. called "-df" for domain file, which would specify the path to a json file containing a dictionary with keys called like bat interfaces and values called like the matching domainname?

**Comment by herbetom** [comment]
For me that sounds like an interesting idea.

**Comment by AiyionPrime** [comment]
I just forgot to hit the comment button two hours ago.
The PR is incoming. :)
