### ISSUE TITLE
allow running mesh-announce as non root

### ISSUE THREAD

**Issue by herbetom** [ffnord/mesh-announce#62]
I would like to run mesh-announce as a user with less permissions then root.

For this to work, as far as I understand it, I need two things::

- allow the "mesh-announce" user to use ports under 1024: 
  https://github.com/Freifunk-Rhein-Neckar/salt/blob/01a7299dd17d76bed5639fd52ff23f9db63ce577/mesh-announce/files/mesh-announce.service.j2#L10-L11
- enable mesh-announce to run `batctl` commands without being root. 
  I was thinking about a sudo wrapper and only allowing the batctl command for that user
  `batctl` is called two times:
  - https://github.com/ffnord/mesh-announce/blob/acee4362d4e8da9edd5bb1b3a63d9182325d4f5a/providers/nodeinfo/network/mesh.py#L16
  - https://github.com/ffnord/mesh-announce/blob/acee4362d4e8da9edd5bb1b3a63d9182325d4f5a/providers/neighbours/batadv.py#L11
 
How bad would it be to put a `sudo` in front of the `batctl` call? Or would we need detection if `sudo` is available, or an config option, ... Whats the best approach for a PR to get accepted? :wink:

**Comment by mweinelt** [comment]
Den Pfad zu batctl in eine Variable auslagen, die conditional auf `os.geteuid() > 0` sudo hinzufügt.
