### ISSUE TITLE
feature: option to override the hostname

### ISSUE THREAD

**Issue by AiyionPrime** [ffnord/mesh-announce#65]
> btw, is there an option to override the hostname?

I don't think so, but with the config file it should be easilier possible to add such an option, since their is to need to add another argc. :smile:

_Originally posted by @herbetom in https://github.com/ffnord/mesh-announce/issues/60#issuecomment-669402551_

This could improve usability on cheap VPS hosts, where hostnames get changed on a regular basis by the hoster.

**Comment by herbetom** [comment]
I did something which just needs another solution for the float conversion: https://github.com/ffnord/mesh-announce/pull/63/files

**Comment by AiyionPrime** [comment]
Looks very promising, another solution differently like what?

**Comment by herbetom** [comment]
IIRC float and the fallback to None are not really compatible or something along those lines.

**Comment by AiyionPrime** [comment]
Not tested this, but the only thing irritating about this is the rather unsafe conversion to float; but as it does this only with localconfig values, it should not be a huge problem, I think.

**Comment by AiyionPrime** [comment]
Just clarify; his code works fine and would resolve this issue.
